import { NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';
import { GoogleGenerativeAI } from '@google/generative-ai'; 
import { Resend } from 'resend'; 

const prisma = new PrismaClient();
const resend = new Resend(process.env.RESEND_API_KEY); 

// 💾 ระบบ Cache จำรายชื่อรุ่น AI 
let cachedFreeModels: string[] = [];
let lastFetchTime = 0;

async function getLiveFreeModels() {
  if (cachedFreeModels.length > 0 && Date.now() - lastFetchTime < 3600000) {
    return cachedFreeModels;
  }
  
  try {
    const res = await fetch("https://openrouter.ai/api/v1/models");
    const data = await res.json();
    
    let freeModels = data.data
      .filter((m: any) => m.id.endsWith(':free'))
      .map((m: any) => m.id);
      
    const prioritize = ["google/gemini-1.5-flash:free", "google/gemini-1.5-pro:free", "meta-llama/llama-3-8b-instruct:free"];
    freeModels = [...new Set([...prioritize, ...freeModels])].filter(id => freeModels.includes(id));

    cachedFreeModels = freeModels;
    lastFetchTime = Date.now();
    return freeModels;
  } catch (e) {
    return ["google/gemini-1.5-flash:free", "meta-llama/llama-3-8b-instruct:free"]; 
  }
}

// 🌐 1. ค้นหาข้อมูลสด 
async function searchWeb(query: string) {
  if (!process.env.SERPER_API_KEY) return "⚠️ ไม่ได้ตั้งค่า SERPER_API_KEY";
  try {
    const res = await fetch("https://google.serper.dev/search", {
      method: "POST",
      headers: {
        "X-API-KEY": process.env.SERPER_API_KEY,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ q: query, gl: "th", hl: "th" })
    });
    const data = await res.json();
    return data.organic?.map((item: any) => `[${item.title}]: ${item.snippet}`).slice(0, 3).join("\n") || "ไม่พบข้อมูลสด";
  } catch (e) {
    return "⚠️ ระบบค้นหาภายนอกขัดข้อง";
  }
}

// 📧 2. ฟังก์ชันส่งอีเมล (TOOL)
async function sendActionEmail(to: string, content: string) {
  if (!process.env.RESEND_API_KEY) return "⚠️ ไม่ได้ตั้งค่า RESEND_API_KEY";
  try {
      const { data, error } = await resend.emails.send({
          from: 'NEXUS-15 <onboarding@resend.dev>', 
          to: [to],
          subject: 'NEXUS-15: Intelligence Update',
          html: `
              <div style="font-family: sans-serif; padding: 20px; border: 1px solid #e0e0e0; border-radius: 10px;">
                  <h2 style="color: #2563eb;">NEXUS-15 Command Center</h2>
                  <p style="font-size: 16px; line-height: 1.6; color: #333;">
                      ${content.replace(/\n/g, '<br/>')}
                  </p>
                  <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                  <footer style="font-size: 12px; color: #888;">
                      This message was automatically generated by NEXUS-15 AI System.
                  </footer>
              </div>
          `,
      });
      if (error) return `❌ ส่งเมลไม่สำเร็จ: ${error.message}`;
      return `✅ ส่งอีเมลสำเร็จ! (ID: ${data?.id})`;
  } catch (e: any) {
      return `❌ Error: ${e.message}`;
  }
}

// 🧠 3. ระบบ Routing Model 
async function callAI(prompt: string, mode: 'core' | 'agent') {
  const targetModels = await getLiveFreeModels();

  for (const modelId of targetModels) {
    try {
      console.log(`📡 [${mode.toUpperCase()}] TRYING: ${modelId}...`);
      const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${process.env.OPENROUTER_API_KEY}`,
          "HTTP-Referer": "http://localhost:3000",
          "X-Title": "Nexus Squad Workflow",
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          model: modelId,
          messages: [{ role: "user", content: prompt }],
          max_tokens: mode === 'core' ? 300 : 4000 
        })
      });

      const result = await response.json();
      
      if (result.choices && result.choices[0].message.content) {
        return result.choices[0].message.content;
      } 
      
    } catch (e) {
      console.error(`❌ [NODE CRASH]: ${modelId}`);
    }
    
    await new Promise(r => setTimeout(r, 1000));
  }
  
  console.log("⚠️ OpenRouter โควตาเต็ม! สลับเครื่องยนต์ไปใช้ Gemini API โดยตรง...");
  if (process.env.GOOGLE_GENERATIVE_AI_API_KEY) {
    const googleModels = ["gemini-2.0-flash", "gemini-1.5-flash-latest", "gemini-1.5-pro", "gemini-pro"];
    
    for (const gModel of googleModels) {
      try {
        console.log(`📡 [GEMINI FALLBACK] TRYING: ${gModel}...`);
        const genAI = new GoogleGenerativeAI(process.env.GOOGLE_GENERATIVE_AI_API_KEY);
        const model = genAI.getGenerativeModel({ model: gModel });
        const result = await model.generateContent(prompt);
        return result.response.text();
      } catch (geminiError: any) {
        console.warn(`⚠️ [GEMINI REJECTED] ${gModel} โดนปฏิเสธ:`, geminiError.message);
      }
    }
  }

  throw new Error("AI โควตาฟรีขัดข้องทั้งหมด โปรดเช็ค API Key ของ OpenRouter หรือ Gemini");
}

// 🔁 4. ฟังก์ชันเรียก AI ซ้ำ
async function callAIUntilFinished(basePrompt: string, previousContent = "", depth = 0): Promise<string> {
  if (depth >= 1) return previousContent; 

  let currentPrompt = basePrompt;
  if (previousContent) {
    currentPrompt = `${basePrompt}\n\n[⚠️ พิมพ์ต่อจากประโยคนี้ให้จบ ห้ามทวนซ้ำ: "${previousContent.slice(-100)}"]`;
  }

  const responseText = await callAI(currentPrompt, 'agent'); 
  const fullText = previousContent + (previousContent ? " " : "") + responseText;

  const isCutOff = responseText.length > 2500 && !/[.!?ๆมาครับค่ะ]$/.test(responseText.trim());

  if (isCutOff) {
    return await callAIUntilFinished(basePrompt, fullText, depth + 1);
  }

  return fullText;
}

export async function POST(req: Request) {
  let missionId = '';
  try {
    const formData = await req.formData();
    let task = formData.get('task') as string;
    const file = formData.get('file') as File | null;

    if (file) {
      const MAX_FILE_SIZE = 1000000; 
      const allowedTypes = ['text/plain', 'text/csv', 'text/markdown', 'application/json'];

      if (file.size > MAX_FILE_SIZE) {
        return NextResponse.json({ error: `ไฟล์ใหญ่เกินไป` }, { status: 400 });
      }

      if (!allowedTypes.includes(file.type) && !file.name.endsWith('.txt') && !file.name.endsWith('.csv')) {
        return NextResponse.json({ error: `รองรับเฉพาะไฟล์ข้อความ` }, { status: 400 });
      }

      const fileContent = await file.text();
      const safeContent = fileContent.substring(0, 5000); 
      
      task = `${task}\n\n[ข้อมูลจากไฟล์แนบ: ${file.name}]\n"""\n${safeContent}...\n"""`;
    }

    const mission = await prisma.task.create({
      data: { title: task.substring(0, 200), status: 'in-progress', progress: 10 }
    });
    missionId = mission.id;

    console.log("🛡️ NEXUS ACTIVE: Operation Initiated");

    let agents: any[] = [];
    let knowledgeDB: any[] = [];
    
    try {
      [agents, knowledgeDB] = await Promise.all([
        prisma.agent.findMany(),
        prisma.knowledge.findMany({ take: 100 }) 
      ]);
    } catch (dbError: any) {
      console.warn("⚠️ Database Sync Warning: ไม่สามารถดึงข้อมูลคลังความรู้ได้");
    }

    const lowerTask = task.toLowerCase().trim();
    
    // 🌟 ระบบสกัดกั้น Action (ป้องกันไม่ให้ Knowledge Engine แย่งงาน!)
    const isEmailRequired = lowerTask.includes("ส่งเมล") || lowerTask.includes("ส่งอีเมล") || lowerTask.includes("@");
    const isChainRequired = lowerTask.includes("เขียน") || lowerTask.includes("โค้ด") || lowerTask.includes("code") || lowerTask.includes("สร้างระบบ");

    // --- 🔍 STEP 0: DATABASE DIRECT MATCH ---
    // จะดึงฐานข้อมูลมาตอบตรงๆ ก็ต่อเมื่อ "ไม่ใช่คำสั่ง Action"
    if (!isEmailRequired && !isChainRequired) {
      const match = knowledgeDB.find((k: any) => {
        const topicKeywords = k.topic.toLowerCase().trim().split(' ');
        return topicKeywords.some((keyword: string) => keyword.length > 2 && lowerTask.includes(keyword));
      });

      if (match) {
        console.log(`🎯 [DATABASE HIT] พบข้อมูลตรงในคลัง: ${match.topic}`);
        
        await prisma.task.update({
          where: { id: missionId },
          data: { 
            status: 'completed', 
            progress: 100, 
            result: match.content, 
            summary: `✅ ข้อมูลถูกดึงโดยตรงจากคลังความรู้หัวข้อ: ${match.topic}` 
          }
        });

        return NextResponse.json({ 
          result: { 
            assignTo: ["KNOWLEDGE ENGINE"], 
            summary: match.content, 
            coreThinking: "พบข้อมูลที่แม่นยำในฐานข้อมูลส่วนตัว ไม่จำเป็นต้องเรียกใช้ AI ภายนอก ⚡", 
            webSearch: "Internal Knowledge Base"
          } 
        });
      }
    }
    // -------------------------------------------------------------

    console.log("🛡️ NEXUS ACTIVE: Starting AI synthesis...");
    
    const squadInfo = agents.map((a: any) => `- ${a.name} (Role: ${a.role})`).join('\n');
    const internalContext = knowledgeDB.slice(0, 5).map((k: any) => `📌 [หมวด ${k.category}] ${k.topic}: ${k.content}`).join('\n');

    // --- STEP 1: CORE ROUTING ---
    const corePrompt = `คุณคือ CORE AI หน้าที่: วิเคราะห์งาน "${task}"
ทีมที่มี:
${squadInfo}

ตอบ JSON สั้นๆ: {"assignTo": "ชื่อเอเจนท์", "needSearch": true/false, "searchQuery": "คำสั้นๆเพื่อค้นหา", "reason": "สรุปสั้นๆ"}`;

    const coreRaw = await callAI(corePrompt, 'core'); 
    const jsonMatch = coreRaw.match(/\{[\s\S]*\}/);
    
    let targetAgent = agents[0] || { name: 'CORE AI', personality: 'ผู้ช่วยอัจฉริยะ', id: 'default' }; 
    let coreReason = "Auto-assigned by Protocol";
    let searchContext = "";
    let usedSearch = false;
    let queryToSearch = null;

    if (jsonMatch) {
      try {
        const coreData = JSON.parse(jsonMatch[0]);
        targetAgent = agents.find((a: any) => a.name === coreData.assignTo) || targetAgent;
        coreReason = coreData.reason || "Direct connection established.";
        
        if (coreData.needSearch && coreData.searchQuery && !isEmailRequired) {
          searchContext = await searchWeb(coreData.searchQuery);
          usedSearch = true;
          queryToSearch = coreData.searchQuery;
        }
      } catch (e) {
        console.log("⚠️ Parse JSON พลาด");
      }
    }

    if(targetAgent.id !== 'default') {
      await prisma.task.update({
        where: { id: missionId },
        data: { agentId: targetAgent.id, progress: 50, searchUsed: usedSearch, searchQuery: queryToSearch }
      });
    }

    // --- 🌟 STEP 2: EXECUTION ENGINE ---
    let finalOutput = "";

    // 📧 กรณีที่ 1: สั่งส่งอีเมล (TOOL CALLING)
    if (isEmailRequired) {
      console.log("🛠️ AGENT ACTION ACTIVATED: EMAIL DISPATCH");
      
      // ดึงอีเมลออกจากคำสั่ง (เช่น ดึง t0980029505@gmail.com ออกมา)
      const emailAddress = lowerTask.match(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/)?.[0];
      
      if (!emailAddress) {
          finalOutput = "❌ ไม่พบที่อยู่อีเมลเป้าหมาย กรุณาระบุอีเมลในคำสั่งด้วยครับ Commander (เช่น ส่งเมลไปที่ customer@example.com)";
      } else {
          console.log(`📧 Dispatching Email to: ${emailAddress}`);
          
          // ให้ Agent ร่างจดหมาย
          const draftPrompt = `คุณคือ BUSINESS MAVEN (Executive Communicator)
          จงร่างเนื้อหาอีเมลเพื่อแจ้งว่า: "${task}"
          ตัดคำว่าส่งเมลออกไป เอาเฉพาะเนื้อหาอีเมลล้วนๆ ใช้ภาษาไทยทางการ สุภาพ`;
          
          const elegantContent = await callAIUntilFinished(draftPrompt);
          const status = await sendActionEmail(emailAddress, elegantContent);
          
          finalOutput = `### 📨 ACTION REPORT: EMAIL DISPATCH\n\n**Status:** ${status}\n**Recipient:** ${emailAddress}\n\n---\n\n**Drafted Content:**\n${elegantContent}`;
          coreReason = "Action Executed: Email Dispatch via Resend API";
          targetAgent = { name: "BUSINESS MAVEN", id: targetAgent.id };
      }
    } 
    // ⛓️ กรณีที่ 2: งานเขียนโค้ด (AGENT CHAIN)
    else if (isChainRequired) {
      console.log("⛓️ AGENT CHAIN ACTIVATED: BYTEFORGE ➡️ CYBERGUARD");
      
      const byteforgePrompt = `คุณคือ BYTEFORGE (Lead Developer)
      งานของคุณคือ: "${task}"
      [ฐานข้อมูลองค์กร]: ${internalContext || "ไม่มีข้อมูล"}
      [ข้อมูล Internet]: ${searchContext || "ไม่ได้ทำการค้นหา"}
      
      จงเขียนโค้ดให้สมบูรณ์ อธิบายสั้นๆ เป็นภาษาไทย และห้ามมีภาษาจีนปนมาเด็ดขาด`;
      
      const codeOutput = await callAIUntilFinished(byteforgePrompt);
      
      console.log("🛡️ PASSING TO CYBERGUARD FOR SECURITY AUDIT...");
      const cyberguardPrompt = `คุณคือ CYBERGUARD (Security Auditor)
      นี่คือโค้ดที่ลูกทีมเพิ่งเขียนเสร็จ:
      ---
      ${codeOutput}
      ---
      หน้าที่ของคุณ: ตรวจสอบความปลอดภัยของโค้ดด้านบน ห้ามเขียนโค้ดใหม่ ให้คอมเมนต์เฉพาะจุดที่อาจเป็นช่องโหว่ อธิบายเป็นภาษาไทยสั้นๆ อ่านง่าย`;
      
      const auditOutput = await callAIUntilFinished(cyberguardPrompt);

      finalOutput = `[SYSTEM MESSAGE]: ดำเนินการผ่าน Multi-Agent Protocol ⛓️\n\n### 💻 [DEVELOPMENT OUTPUT: BYTEFORGE]\n${codeOutput}\n\n---\n\n### 🛡️ [SECURITY AUDIT: CYBERGUARD]\n${auditOutput}`;
      coreReason = "Multi-Agent Chain Completed: Code Generation + Security Verification";
      targetAgent = { name: "BYTEFORGE & CYBERGUARD", id: targetAgent.id }; 

    } 
    // 👤 กรณีที่ 3: คำถามทั่วไป (SINGLE AGENT)
    else {
      console.log("👤 SINGLE AGENT ACTIVATED");
      const agentPrompt = `คุณคือ ${targetAgent.name} (บุคลิก: ${targetAgent.personality})
      [ฐานข้อมูลองค์กร]: ${internalContext || "ไม่มีข้อมูล"}
      [ข้อมูล Internet]: ${searchContext || "ไม่ได้ทำการค้นหา"}

      คำสั่งจากผู้ใช้: "${task}"

      ⚠️ กฎเหล็กในการตอบ:
      1. จงตอบเป็น "ภาษาไทย" ที่ถูกต้อง สละสลวย
      2. ห้ามใช้ภาษาจีน หรือภาษาอื่นๆ ปนมาเด็ดขาด 
      3. ตรวจทานการพิมพ์ให้ถูกต้อง 100%`;

      finalOutput = await callAIUntilFinished(agentPrompt);
    }

    // --- STEP 3: UPDATE DB & RETURN ---
    await prisma.task.update({
      where: { id: missionId },
      data: { status: 'completed', progress: 100, result: finalOutput, summary: coreReason }
    });

    return NextResponse.json({ 
      result: { 
        assignTo: [targetAgent.name], 
        summary: finalOutput, 
        coreThinking: coreReason,
        webSearch: usedSearch ? `ค้นหาเรื่อง: ${queryToSearch}` : "ใช้ข้อมูลภายใน"
      } 
    });

  } catch (error: any) {
    console.error("🔥 TOTAL SYSTEM FAILURE:", error.message);
    if (missionId) {
      await prisma.task.update({ where: { id: missionId }, data: { status: 'failed', summary: error.message, progress: 100 } });
    }
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}